project_name: 'amb-feedback-bot'
repo: 'git@github.com:amb-code/{{ project_name }}.git'
deployment_dir: '/home/docker/feedback-bot'

tag: "{{ lookup('ansible.builtin.env', 'TAG') }}"
env_name: "{{ lookup('ansible.builtin.env', 'ENVIRONMENT') }}"
stage: "{{ lookup('ansible.builtin.env', 'STAGE') }}"

db_username: "{{ lookup('ansible.builtin.env', 'DB_USERNAME') }}"
db_password: "{{ lookup('ansible.builtin.env', 'DB_PASSWORD') }}"

tg_token: "{{ lookup('ansible.builtin.env', 'TG_TOKEN') }}"
tg_chat_id: "{{ lookup('ansible.builtin.env', 'TG_CHAT_ID') }}"

sentry_dsn: "{{ lookup('ansible.builtin.env', 'SENTRY_DSN') }}"