all:
  hosts:
    main:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TARGET_SERVER') }}"
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/infra-internal
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_user: root
    amb:
      ansible_host: "{{ lookup('ansible.builtin.env', 'TARGET_SERVER') }}"
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/infra-internal
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_user: root
